### ISSUE TITLE
Upgrade to 4.2.2 fails because of pcre2 not found

### ISSUE THREAD

**Issue by pascaloettli** [sethrfore/homebrew-r-srf#57] opened 2022-11-10 01:44 UTC
Laptop:
> MacBook Air (M2, 2022)
> Platform: aarch64-apple-darwin21.6.0 (64-bit)
> Running under: macOS Monterey 12.6

Upgrade from  `4.2.1` to `4.2.2_1` with options `--with-libtiff --with-openblas --with-openjdk --with-cairo-x11 --with-tcl-tk-x11` fails with the following error:

```
Last 15 lines from /Users/pascaloettli/Library/Logs/Homebrew/r/02.make:
making inlined.d from inlined.c
making inspect.d from inspect.c
making internet.d from internet.c
making iosupport.d from iosupport.c
making lapack.d from lapack.c
making list.d from list.c
grep.c:73:10: fatal error: 'pcre2.h' file not found
# include<pcre2.h>
         ^~~~~~~~~
1 error generated.
make[2]: *** [grep.d] Error 1
make[2]: *** Waiting for unfinished jobs....
making localecharset.d from localecharset.c
make[1]: *** [R] Error 1
make: *** [R] Error 1
```

**Comment by sethrfore** [comment] 2022-11-10 14:16
Try reinstalling `pcre2` or all R dependencies with something like `brew deps -n sethrfore/r-srf/r | xargs brew reinstall` prior to compiling R.  

The version bump to 4.2.2 also included formula edits to address build errors with the current `macOSX13.sdk` as discussed [here](https://github.com/sethrfore/homebrew-r-srf/discussions/40#discussioncomment-4067559). 

Depending on which Xcode and Command Line Tools you have installed, these edits could crash your install. If reinstalling dependencies doesn't work, comment out lines 39-43 in the formula and see what happens. 

Let me know what you find out. Thanks.

**Comment by pascaloettli** [comment] 2022-11-11 02:45
> Try reinstalling `pcre2`

This is what I have first done yesterday but it didn't solve the problem

> The version bump to 4.2.2 also included formula edits to address build errors with the current macOSX13.sdk as discussed https://github.com/sethrfore/homebrew-r-srf/discussions/40#discussioncomment-4067559.

Sorry, I missed this discussion

>  If reinstalling dependencies doesn't work, comment out lines 39-43 in the formula and see what happens

This is a summary of what happens, so far:

|| Original r.rb file | With lines 39-43 commented |
| --- | :---: | :---: |
| default options | X<sup>[1]</sup> | O |
| adding `--with-openblas` only| X<sup>[1]</sup> | X<sup>[2]</sup> |
| adding `--with-openjdk` only| X<sup>[1]</sup> | X<sup>[2]</sup> |
|adding `--with-cairo-x11` only|X<sup>[1]</sup>|X<sup>[1]</sup>|

<details>
<summary>[1]</summary>

```
Last 15 lines from /Users/pascaloettli/Library/Logs/Homebrew/r/02.make:
making list.d from list.c
making logic.d from logic.c
making localecharset.d from localecharset.c
grep.c:73:10: fatal error: 'pcre2.h' file not found
# include<pcre2.h>
         ^~~~~~~~~
making main.d from main.c
1 error generated.
make[2]: *** [grep.d] Error 1
make[2]: *** Waiting for unfinished jobs....
making mapply.d from mapply.c
making mask.d from mask.c
making match.d from match.c
make[1]: *** [R] Error 1
make: *** [R] Error 1
```
</details>

<details>
<summary>[2]</summary>

```
Last 15 lines from /Users/pascaloettli/Library/Logs/Homebrew/r/02.make:
clang -I"../../../../include" -DNDEBUG -I../../../include -I../../../../src/include -DHAVE_CONFIG_H -I../../../../src/main  -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/xz/include   -fPIC  -g -O2  -c getfmts.c -o getfmts.o
clang -I"../../../../include" -DNDEBUG -I../../../include -I../../../../src/include -DHAVE_CONFIG_H -I../../../../src/main  -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/xz/include   -fPIC  -g -O2  -c http.c -o http.o
clang -I"../../../../include" -DNDEBUG -I../../../include -I../../../../src/include -DHAVE_CONFIG_H -I../../../../src/main  -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/xz/include   -fPIC  -g -O2  -c gramLatex.c -o gramLatex.o
clang -I"../../../../include" -DNDEBUG -I../../../include -I../../../../src/include -DHAVE_CONFIG_H -I../../../../src/main  -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/xz/include   -fPIC  -g -O2  -c gramRd.c -o gramRd.o
clang -I"../../../../include" -DNDEBUG -I../../../include -I../../../../src/include -DHAVE_CONFIG_H -I../../../../src/main  -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/xz/include   -fPIC  -g -O2  -c pdscan.c -o pdscan.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L../../../../lib -L/opt/homebrew/opt/gettext/lib -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/xz/lib -o tools.so text.o init.o Rmd5.o md5.o signals.o install.o getfmts.o http.o gramLatex.o gramRd.o pdscan.o -L../../../../lib -lR -lintl -Wl,-framework -Wl,CoreFoundation
mkdir ../../../../library/tools/libs
installing 'sysdata.rda'
/bin/sh: line 1: 51987 Done                    echo "tools:::sysdata2LazyLoadDB(\"./R/sysdata.rda\",\"../../../library/tools/R\")"
     51988 Killed: 9               | R_DEFAULT_PACKAGES=NULL LC_ALL=C R_ENABLE_JIT=0 TZ=UTC ../../../bin/R --vanilla --no-echo
make[4]: *** [sysdata] Error 137
make[3]: *** [all] Error 2
make[2]: *** [R] Error 1
make[1]: *** [R] Error 1
make: *** [R] Error 1
```
</details>

**Comment by sethrfore** [comment] 2022-11-11 14:57
I haven't had any of these errors myself. It seems like a problem isolated to your system. I would run `brew doctor` and see if anything problems are detected with your homebrew installation. I would also check your .Rprofile and .Renviron files as well as any other relevant dot files that might be affecting your build environment. It also could be that you have old files hanging around from previous R (binary/cask version) installation. If nothing works you could try a fresh homebrew installation... Other than that, I don't have any other immediate suggestions. Let me know what happens.

**Comment by sethrfore** [comment] 2022-11-11 15:01
Also check which version of cairo you have installed. I have the homebrew version installed but I think there is a cairo formula in my repo. I haven't used it in a while and it could be causing problems??

**Comment by jd-a** [comment] 2022-11-11 16:10
I cannot reproduce this error (on an Intel machine with macOS 12). You might try to build R (not the package but from source) from "brew sh" to have some more control/insight.

**Comment by pascaloettli** [comment] 2022-11-14 00:42
Thank you for the comments. When I have time, I will try with a clean profile and come back to you with the outputs.

**Comment by sethrfore** [comment] 2022-11-14 19:22
Ok, I'm going to close the issue and we'll reopen it if necessary when the time comes.

**Closed by sethrfore** 2022-11-14 19:22 UTC

**Comment by halterc** [comment] 2023-01-12 10:59
Hi sethrfore,

Same problem here. Running macOS Ventura 13.1 on a MacBook M1. Error code is the same.


brew install -s sethrfore/r-srf/r --with-openblas
==> Fetching sethrfore/r-srf/r
==> Downloading https://cran.r-project.org/src/base/R-4/R-4.2.2.tar.gz
Already downloaded: /Users/userABC/Library/Caches/Homebrew/downloads/2cc35deb74316557f5bf075f5d775cd8214dbd01e31595613b6c366b27fec93f--R-4.2.2.tar.gz
==> Installing r from sethrfore/r-srf
==> ./configure --prefix=/opt/homebrew/Cellar/r/4.2.2_1 --enable-memory-profilin
==> make
Last 15 lines from /Users/userABC/Library/Logs/Homebrew/r/02.make:
making lapack.d from lapack.c
making list.d from list.c
making localecharset.d from localecharset.c
making logic.d from logic.c
grep.c:73:10: fatal error: 'pcre2.h' file not found
# include<pcre2.h>
         ^~~~~~~~~
1 error generated.
make[2]: *** [grep.d] Error 1
make[2]: *** Waiting for unfinished jobs....
making mapply.d from mapply.c
making main.d from main.c
making mask.d from mask.c
make[1]: *** [R] Error 1
make: *** [R] Error 1

I also tried reinstalling pcre2 freshly but to no avail.
Also linking pcre2.h to many different paths (accessed by brew) did not work.

Any help is greatly appreciated. :)
