### ISSUE TITLE
Can't build R when using cairo-x11 formula

### ISSUE THREAD

**Issue by alazarolop** [sethrfore/homebrew-r-srf#39] opened 2021-01-13 22:34 UTC
Hi, 

I have some formulas depending on `cairo` from core and I was getting issues when upgrading them and their dependencies. 
I also saw `cairo-x11` new formula in the tap and so I tried to use it and avoid the issues, although I wasn't sure if its usage was already implemented in `r`.

When building R during `./configure` I got this error:

```
checking X11/Intrinsic.h usability... no
checking X11/Intrinsic.h presence... yes
configure: WARNING: X11/Intrinsic.h: present but cannot be compiled
configure: WARNING: X11/Intrinsic.h:     check for missing prerequisite headers?
configure: WARNING: X11/Intrinsic.h: see the Autoconf documentation
configure: WARNING: X11/Intrinsic.h:     section "Present But Cannot Be Compiled"
configure: WARNING: X11/Intrinsic.h: proceeding with the compiler's result
configure: WARNING:     ## ----------------------------------------- ##
configure: WARNING:     ## Report this to https://bugs.r-project.org ##
configure: WARNING:     ## ----------------------------------------- ##
checking for X11/Intrinsic.h... no
configure: error: --with-x=yes (default) and X11 headers/libs are not available
/usr/bin/curl --version
/usr/libexec/java_home --xml --failfast
/usr/libexec/java_home --xml --failfast
```

I thought it could be related to `cairo-x11` not being linked by design. So I added some flags to the formula `r` formula, but I got the same error eventually.

```
if build.with? "cairo-x11"
      args << "--with-cairo"
      ENV.append "CPPFLAGS", "-I#{Formula["cairo-x11"].opt_include}"
      ENV.append "LDFLAGS", "-L#{Formula["cairo-x11"].opt_lib}"
else
      args << "--without-cairo"
end
```

I was wondering whether `cairo-11` usage is enable in R formula at this moment. If not, if there a way to fix this? I would be happy to test it and PR it in case it works. 

Thank you

**Comment by ashimog** [comment] 2021-01-14 03:31
Got the same problem here.

I found that if I specified the X11 headers to those shipped with XQuartz, then R will compile.
However doing so will result in all packages that require tcl-tk will fail to build. Loading the `tcltk` package will cause R to immediately crash.

My `brew config`:

```
HOMEBREW_VERSION: 2.7.3-31-g028e733
ORIGIN: https://github.com/Homebrew/brew
HEAD: 028e733e79c37724bc2d36238fd18e3763ccef9d
Last commit: 20 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 18218c53db1b546f585b731dc81730703381b9eb
Core tap last commit: 21 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: /usr/local/bin/vim
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.271.09, 1.8.0_66
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
XQuartz: 2.7.11 => /opt/X11
```

**Comment by sethrfore** [comment] 2021-01-14 14:08
Thanks, I'm looking into it now.

**Comment by sethrfore** [comment] 2021-01-16 22:52
The problem should be fixed for the most part. The problem was caused by the fact that python@3.9 is now built with tcl-tk which affected glib and subsequent cairo-x11 builds. This in turn exposed Homebrews non-x11 tcl-tk when build r resulting in the meltdown. 

Really fixing the problem likely requires creating new formula for at least python@3.9 and glib and potentially other upstream dependencies but this leads to duplicate formulas and all kinds of other issues. 

The 'fix' I opted for was simple removing the glib dependency from the cairo-x11 formula. I'm not sure exactly how this affects cairo and r. They both build successfully on my machine but certain functionality might be affected. 

The flat out truth is X11 is outdated. The reduced number of compiling options being provided by standard Homebrew formulas makes maintaining this formula a snowballing issue where getting successful r builds requires modifying an increasing number of upstream direct and indirect dependencies.

The vast majority of issues raised for this formula have been related to X11. Because the number and difficulty of fixing new issues seems likely to increase, I'm not certain that I personally have much interest in continuing to support it. I'm only posting this notice here for those that might be following this issue. I will likely raise a new issue that addresses this more directly. Just fyi...

**Comment by sethrfore** [comment] 2021-01-17 18:50
For all following or interested in this issue: see R/X11 deprecation notice in README. For discussion, comments and all future notices concerning this issue, refer to this [discussion thread](https://github.com/sethrfore/homebrew-r-srf/discussions/40).

**Comment by luispuerto** [comment] 2021-01-17 20:07
I'm on the same boat, but I don't thin I'm for the same reason

```
Last 15 lines from /Users/lpuerto/Library/Logs/Homebrew/r/02.make:
making printutils.d from printutils.c
making qsort.d from qsort.c
making radixsort.d from radixsort.c
making random.d from random.c
making raw.d from raw.c
making registration.d from registration.c
making relop.d from relop.c
platform.c:3203:12: fatal error: 'unicode/uversion.h' file not found
#  include <unicode/uversion.h>
           ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [platform.d] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [R] Error 1
make: *** [R] Error 1
```

**Comment by sethrfore** [comment] 2021-01-17 20:55
You were installing cairo-x11 formula?

I just rebuilt everything without errors.

```
❯ brew config
HOMEBREW_VERSION: 2.7.5-10-g8869208
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8869208a601b7846f2e6597a49b4740cb3c06de2
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ab283f7fffa3f0b750dac0f17a0fbcf31f5c6300
Core tap last commit: 61 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.qp1X7ziAWl/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/subl
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_EMOJI: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_275
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
XQuartz: 2.7.11 => /opt/X11
```

**Comment by luispuerto** [comment] 2021-01-17 21:05
Yes AFAIK! 

```
brew config
HOMEBREW_VERSION: 2.7.5-10-g8869208
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8869208a601b7846f2e6597a49b4740cb3c06de2
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9bb1a7cc9492e7aafc6c80f75810c3f5721b1578
Core tap last commit: 24 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.E50aEPpFXz/org.macosforge.xquartz:0
HOMEBREW_EDITOR: subl
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.2, 14.0.1, 14
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
XQuartz: 2.7.11 => /opt/X11
```

I just installed it manually and rerun: 

```
brew install sethrfore/r-srf/r --with-openblas --with-openjdk --with-libtiff --with-cairo-x
11
==> Installing r from sethrfore/r-srf
==> Downloading https://cloud.r-project.org/src/base/R-4/R-4.0.3.tar.gz
Already downloaded: /Users/lpuerto/Library/Caches/Homebrew/downloads/ab933519cc34924f48331f233020adc2a0f9688fc901083518685b12e82372fa--R-4.0.3.tar.gz
==> ./configure --prefix=/usr/local/Cellar/r/4.0.3 --enable-memory-profiling --with-x --with-aqua --
==> make
Last 15 lines from /Users/lpuerto/Library/Logs/Homebrew/r/02.make:
making printutils.d from printutils.c
making qsort.d from qsort.c
making radixsort.d from radixsort.c
making random.d from random.c
making raw.d from raw.c
making registration.d from registration.c
making relop.d from relop.c
platform.c:3203:12: fatal error: 'unicode/uversion.h' file not found
#  include <unicode/uversion.h>
           ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [platform.d] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [R] Error 1
make: *** [R] Error 1
```

**Comment by luispuerto** [comment] 2021-01-17 21:08
I guess it isn't your cairo fomula… I tried to build now without `--with-cairo-x11` and it through the same error

**Comment by sethrfore** [comment] 2021-01-17 21:08
Whats the output of `brew config`?

It might help uninstall r, reinstall all r dependencies and then try installing R again.

`brew deps --union sethrfore/r-srf/cairo-x11 sethrfore/r-srf/r | xargs brew reinstall`

**Comment by luispuerto** [comment] 2021-01-17 21:13
> Whats the output of `brew config`?

I've already posted it 😛 More or less the same as yours.

**Comment by sethrfore** [comment] 2021-01-17 21:14
It also might have something to do with any .Renviron, Makevars or other config files lying around.

Got it, your post musta posted while I was still writing :)

**Comment by btskinner** [comment] 2021-01-28 16:13
@luispuerto were you able to get a fix? I'm having the same error as you and haven't been able to install despite playing around with various configurations / reinstallations.

```
platform.c:3203:12: fatal error: 'unicode/uversion.h' file not found
#  include <unicode/uversion.h>
           ^~~~~~~~~~~~~~~~~~~~
1 error generated.
```

```
$ brew config
HOMEBREW_VERSION: 2.7.7-2-gca4a444
ORIGIN: https://github.com/Homebrew/brew
HEAD: ca4a4449ad6a64bff13b7d817e011e0cb63eabdd
Last commit: 25 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4793b90eb5141fa9f73b817bd81e220f3dc238e9
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.RU3ntOM0Um/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /Applications/Emacs.app/Contents/MacOS/Emacs
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 15.0.2, 12.0.2, 1.8.0_282
macOS: 11.1-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
XQuartz: 2.7.11 => /opt/X11
```

**Comment by luispuerto** [comment] 2021-01-28 19:00
@btskinner I decided to stop using this tap and use instead the binary linking against openBLAS from homebrew. I haven't checked how it the benchmarking yet. My wife and I have similar mac models and she still have the R from this tap, so I can do a quite good comparison. I have to say that she is also having a similar error when she tries to update using homebrew. 

I don't know how it's going to benchmark with the linking, but at least till now I have to almost reinstall all the packages and some of them needed to be build from source to really work. So I guess the linking is working.

**Comment by sethrfore** [comment] 2021-01-29 14:52
@btskinner R builds cleanly for me and tcl-tk-x11 appears functional. I'm not sure what the issue is. I guess I would try reinstalling xquartz and then run:
`brew deps -n --union sethrfore/r-srf/cairo-x11 sethrfore/r-srf/r | xargs brew reinstall`
`brew reinstall -s cairo-x11`
Then try reinstalling r with your selected options. Here is my brew config:
```
❯ brew config
HOMEBREW_VERSION: 2.7.7-34-g0a46e34
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0a46e340241fc5eef203f2ef30eff883b8bbbf13
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7dcbcf2f4a86ad8c92d705905ca892a313340bd3
Core tap last commit: 83 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.q7lhd7M1VP/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/subl
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_EMOJI: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_282
macOS: 11.1-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
XQuartz: 2.7.11 => /opt/X11
```

**Comment by btskinner** [comment] 2021-01-29 15:40
Thanks @sethrfore and @luispuerto. I've tried what you said, @sethrfore, and got nowhere. 

I've has issues for a while with cairo, R, other home-brew spatial tools. It's 100% not your fault, just a fundamental mismatch between various softwares and the speed at which they are deprecating reliance on X11. I really appreciate all that you've done with this project and totally understand that the juice may not be worth the squeeze any more.

The good news is that I built R using Homebrew's regular `brew install -s r` and it appears to have linked with OpenBLAS on my system, which what I really care about.

```r
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin20.2.0 (64-bit)
Running under: macOS  11.1

Matrix products: default
BLAS:   /usr/local/Cellar/openblas/0.3.13/lib/libopenblasp-r0.3.13.dylib
LAPACK: /usr/local/Cellar/r/4.0.3_2/lib/R/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3
```

And with a couple of speed tests from https://mpopov.com/blog/2019/06/04/faster-matrix-math-in-r-on-macos/
### Test 1
```r
library(microbenchmark)
d <- 1e3
x <- matrix(rnorm(d^2), d, d)
microbenchmark(tcrossprod(x), solve(x), svd(x), times = 10L)
```
```r
Unit: milliseconds
          expr        min         lq       mean    median        uq       max neval
 tcrossprod(x)   6.404492   6.485909   9.656052   8.50035  10.08247  23.17912    10
      solve(x)  38.029609  40.102224  43.152805  42.37321  43.69523  57.35198    10
        svd(x) 635.265589 642.495579 648.427817 650.45007 652.48617 660.36512    10
```
### Test 2

```r
library(microbenchmark)
set.seed(20190604)
n <- 1e3
p <- 1e2
b <- rnorm(p + 1, 0, 10)
x <- matrix(runif(n * p, -10, 10), ncol = p, nrow = n)
y <- cbind(1, x) %*% b + rnorm(n, 0, 2)
microbenchmark(lm(y ~ x))
```
```r
Unit: milliseconds
      expr      min      lq     mean   median       uq      max neval
 lm(y ~ x) 3.351647 3.46696 4.340163 3.553408 4.555379 12.38549   100
```
I might end up using a modified version of your tap so I can also use the Accelerate LAPACK, but I haven't done so yet.

**Comment by sethrfore** [comment] 2021-01-29 16:27
@btskinner yeah, x11 seems to result in ongoing issues... I also wanted to mention that I pushed a new branch (r-aqua) which is pretty much what I've been using on my personal computer for a while now. It is similar to Homebrew R formula inasmuch as it does not rely on X11 but it does incorporate openblas (for blas and lapack libraries), java as well as several other options based on core Homebrew formulas. There is also a line that can be uncommented if you want mactex functionality. This install tends to be much more reliable plus its got several other perks compared to the Homebrew R formula. Just FYI, but you should use whatever formula works best!

**Comment by luispuerto** [comment] 2021-01-30 11:54
@btskinner Here are my benchmarks. I have… 

<img width="698" alt="Screen Shot 2021-01-30 at 12 42 29" src="https://user-images.githubusercontent.com/22882880/106355514-b0a5cf00-62f8-11eb-86c7-e9874061d1fa.png">

Which one is your for comparison? 

``` r
sessionInfo()
#> R version 4.0.3 (2020-10-10)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Big Sur 10.16
#> 
#> Matrix products: default
#> BLAS:   /usr/local/Cellar/openblas/0.3.13/lib/libopenblasp-r0.3.13.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] rstudioapi_0.13   knitr_1.31        magrittr_2.0.1    rlang_0.4.10     
#>  [5] fansi_0.4.2       stringr_1.4.0     styler_1.3.2      highr_0.8        
#>  [9] tools_4.0.3       xfun_0.20         sessioninfo_1.1.1 cli_2.2.0        
#> [13] withr_2.4.1       htmltools_0.5.1.1 ellipsis_0.3.1    yaml_2.2.1       
#> [17] digest_0.6.27     assertthat_0.2.1  tibble_3.0.6      lifecycle_0.2.0  
#> [21] crayon_1.3.4      purrr_0.3.4       vctrs_0.3.6       fs_1.5.0         
#> [25] glue_1.4.2        evaluate_0.14     rmarkdown_2.6     reprex_1.0.0     
#> [29] stringi_1.5.3     compiler_4.0.3    pillar_1.4.7      backports_1.2.1  
#> [33] pkgconfig_2.0.3

library(microbenchmark)
d <- 1e3
x <- matrix(rnorm(d^2), d, d)
microbenchmark(tcrossprod(x), solve(x), svd(x), times = 10L)
#> Unit: milliseconds
#>           expr        min         lq      mean    median        uq       max
#>  tcrossprod(x)   8.198306   9.885778  10.32444  10.42378  10.94228  11.79540
#>       solve(x)  39.913271  41.777837  47.59014  46.46908  49.96189  60.05647
#>         svd(x) 529.568849 547.976878 585.89679 568.02913 611.98915 707.27970
#>  neval
#>     10
#>     10
#>     10

library(microbenchmark)
set.seed(20190604)
n <- 1e3
p <- 1e2
b <- rnorm(p + 1, 0, 10)
x <- matrix(runif(n * p, -10, 10), ncol = p, nrow = n)
y <- cbind(1, x) %*% b + rnorm(n, 0, 2)
microbenchmark(lm(y ~ x))
#> Unit: milliseconds
#>       expr      min       lq     mean   median       uq      max neval
#>  lm(y ~ x) 3.519495 4.673732 5.470311 5.097688 5.913175 11.94613   100
```

<sup>Created on 2021-01-30 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.3 (2020-10-10)
#>  os       macOS Big Sur 10.16         
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Europe/Zurich               
#>  date     2021-01-30                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package        * version date       lib source        
#>  assertthat       0.2.1   2019-03-21 [1] CRAN (R 4.0.2)
#>  backports        1.2.1   2020-12-09 [1] CRAN (R 4.0.2)
#>  cli              2.2.0   2020-11-20 [1] CRAN (R 4.0.2)
#>  crayon           1.3.4   2017-09-16 [1] CRAN (R 4.0.2)
#>  digest           0.6.27  2020-10-24 [1] CRAN (R 4.0.2)
#>  ellipsis         0.3.1   2020-05-15 [1] CRAN (R 4.0.2)
#>  evaluate         0.14    2019-05-28 [1] CRAN (R 4.0.1)
#>  fansi            0.4.2   2021-01-15 [1] CRAN (R 4.0.2)
#>  fs               1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
#>  glue             1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
#>  highr            0.8     2019-03-20 [1] CRAN (R 4.0.2)
#>  htmltools        0.5.1.1 2021-01-22 [1] CRAN (R 4.0.3)
#>  knitr            1.31    2021-01-27 [1] CRAN (R 4.0.3)
#>  lifecycle        0.2.0   2020-03-06 [1] CRAN (R 4.0.2)
#>  magrittr         2.0.1   2020-11-17 [1] CRAN (R 4.0.2)
#>  microbenchmark * 1.4-7   2019-09-24 [1] CRAN (R 4.0.2)
#>  pillar           1.4.7   2020-11-20 [1] CRAN (R 4.0.2)
#>  pkgconfig        2.0.3   2019-09-22 [1] CRAN (R 4.0.2)
#>  purrr            0.3.4   2020-04-17 [1] CRAN (R 4.0.2)
#>  reprex           1.0.0   2021-01-27 [1] CRAN (R 4.0.3)
#>  rlang            0.4.10  2020-12-30 [1] CRAN (R 4.0.2)
#>  rmarkdown        2.6     2020-12-14 [1] CRAN (R 4.0.2)
#>  rstudioapi       0.13    2020-11-12 [1] CRAN (R 4.0.2)
#>  sessioninfo      1.1.1   2018-11-05 [1] CRAN (R 4.0.2)
#>  stringi          1.5.3   2020-09-09 [1] CRAN (R 4.0.2)
#>  stringr          1.4.0   2019-02-10 [1] CRAN (R 4.0.2)
#>  styler           1.3.2   2020-02-23 [1] CRAN (R 4.0.2)
#>  tibble           3.0.6   2021-01-29 [1] CRAN (R 4.0.3)
#>  vctrs            0.3.6   2020-12-17 [1] CRAN (R 4.0.2)
#>  withr            2.4.1   2021-01-26 [1] CRAN (R 4.0.3)
#>  xfun             0.20    2021-01-06 [1] CRAN (R 4.0.2)
#>  yaml             2.2.1   2020-02-01 [1] CRAN (R 4.0.2)
#> 
#> [1] /Users/lpuerto/Library/R/4.x/library
#> [2] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

</details>

A couple of comments… If I run `sessionInfo()` outside of `repex` package doesn't show the openBLAS link. 

```r 
sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reprex_1.0.0         microbenchmark_1.4-7

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13   knitr_1.31        magrittr_2.0.1    R6_2.5.0         
 [5] rlang_0.4.10      fansi_0.4.2       styler_1.3.2      highr_0.8        
 [9] tools_4.0.3       xfun_0.20         cli_2.2.0         withr_2.4.1      
[13] clipr_0.7.1       htmltools_0.5.1.1 ellipsis_0.3.1    yaml_2.2.1       
[17] assertthat_0.2.1  digest_0.6.27     tibble_3.0.6      lifecycle_0.2.0  
[21] crayon_1.3.4      processx_3.4.5    callr_3.5.1       purrr_0.3.4      
[25] ps_1.5.0          vctrs_0.3.6       fs_1.5.0          glue_1.4.2       
[29] evaluate_0.14     rmarkdown_2.6     compiler_4.0.3    pillar_1.4.7     
[33] backports_1.2.1   pkgconfig_2.0.3  
```

**Comment by btskinner** [comment] 2021-01-30 17:06
@sethrfore, that's really helpful. I'll check it out.

@luispuerto, here's what I have:

- MacBook Pro (15-inch, 2018)
- Processor: 2.9 GHz 6-Core Intel Core i9
- Memory: 32 GB 2400 MHz DDR4

**Comment by luispuerto** [comment] 2021-01-30 17:39
@btskinner well… you benchmarks and mine aren't that different and on some parts yours are better and on others are mine. I guess that if we run more complicated one, things were more different… but I really don't know if it's worth to go through all the trouble of building R to have something that looks really similar to the binary when you just link openBLAS.

**Closed** 2021-08-16 13:08 UTC
